CREATE TABLE dbo.Users
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_dbo_Users_Id PRIMARY KEY CLUSTERED,
	Name VARCHAR(50) NULL,
	Login CHAR(12) NULL,
	IsActive BIT NOT NULL CONSTRAINT DF_IsActive DEFAULT 1,
	SourceId INT NOT NULL,
	SourceSystemId TINYINT NOT NULL,
	IsDeleted BIT NOT NULL CONSTRAINT DF_IsDeleted DEFAULT 0,
	InsertedAuditId INT NOT NULL,
	UpdatedAuditId INT NOT NULL
)