CREATE TABLE meta.Audit
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_meta_Audit PRIMARY KEY,
	PackageId SMALLINT NOT NULL,
	DtStarted DATETIME2(0) CONSTRAINT DF_meta_Audit_DtStarted DEFAULT SYSDATETIME(),
	DtFinished DATETIME2(0)

)
